#!/usr/bin/env bash
# pipeline-helpers.sh — Shared helper functions for the RND pipeline (bash port).
# Source this file:  source "$(dirname "$0")/lib/pipeline-helpers.sh"

set -euo pipefail

# ---------------------------------------------------------------------------
# State management
# ---------------------------------------------------------------------------

read_json_file() {
    local path="$1"
    if [[ ! -f "$path" ]]; then
        echo ""
        return 1
    fi
    cat "$path"
}

read_pipeline_state() {
    local run_dir="$1"
    local state_path="$run_dir/state.json"
    if [[ -f "$state_path" ]]; then
        cat "$state_path"
    else
        echo ""
    fi
}

write_pipeline_state() {
    local run_dir="$1"
    local state_json="$2"
    echo "$state_json" > "$run_dir/state.json"
}

# jq-based helpers for state manipulation
set_phase_status() {
    local state_json="$1"
    local phase="$2"
    local status="$3"
    echo "$state_json" | jq --arg p "$phase" --arg s "$status" '.phase_status[$p] = $s'
}

get_phase_status() {
    local state_json="$1"
    local phase="$2"
    echo "$state_json" | jq -r --arg p "$phase" '.phase_status[$p] // empty'
}

get_json_field() {
    local json="$1"
    local field="$2"
    echo "$json" | jq -r ".$field // empty"
}

get_json_field_raw() {
    local json="$1"
    local field="$2"
    echo "$json" | jq ".$field"
}

# ---------------------------------------------------------------------------
# Blocker log (one JSON object per line — easy to grep / tail)
# ---------------------------------------------------------------------------

add_blocker_log() {
    local run_dir="$1"
    local phase="$2"
    local reason="$3"
    local meta="${4:-}"
    local ts
    ts=$(date -Iseconds 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z')
    local entry
    if [[ -n "$meta" ]]; then
        entry=$(jq -nc --arg ts "$ts" --arg p "$phase" --arg r "$reason" --argjson m "$meta" \
            '{ts:$ts, phase:$p, reason:$r, meta:$m}')
    else
        entry=$(jq -nc --arg ts "$ts" --arg p "$phase" --arg r "$reason" \
            '{ts:$ts, phase:$p, reason:$r}')
    fi
    echo "$entry" >> "$run_dir/blocker_log.jsonl"
}

# ---------------------------------------------------------------------------
# Fallback stub output — always writes a non-empty file
# ---------------------------------------------------------------------------

write_stub_output() {
    local run_dir="$1"
    local filename="$2"
    local phase="$3"
    local reason="$4"
    local path="$run_dir/$filename"
    local leaf_name
    leaf_name=$(basename "$filename" .md)
    local now
    now=$(date '+%Y-%m-%d %H:%M:%S')

    cat > "$path" <<EOF
# $leaf_name (STUB — auto-generated by pipeline)

## Status: BLOCKED

| Field     | Value |
|-----------|-------|
| Phase     | $phase |
| Reason    | $reason |
| Generated | $now |

## Best-effort content

No content could be generated for this phase in this run.
Re-run with \`--resume\` once the blocker is resolved.

## Downstream: Safe to proceed

The pipeline has written this stub so that downstream phases can start
with partial context rather than failing on a missing input file.
EOF
    echo "    [STUB] Written: $filename"
}

# ---------------------------------------------------------------------------
# Retry wrapper with exponential back-off
# ---------------------------------------------------------------------------

invoke_with_retry() {
    local label="$1"
    local max_attempts="${2:-3}"
    local base_delay="${3:-30}"
    shift 3
    local cmd=("$@")

    for (( i=1; i<=max_attempts; i++ )); do
        if "${cmd[@]}" 2>&1; then
            return 0
        else
            local msg="exit code $?"
            echo "    [ATTEMPT $i/$max_attempts] $label — $msg"
            if (( i < max_attempts )); then
                local delay=$(( base_delay * (1 << (i-1)) ))
                echo "    Waiting ${delay}s before next attempt..."
                sleep "$delay"
            fi
        fi
    done
    echo "    [EXHAUSTED] Max retries reached for: $label"
    return 1
}

# ---------------------------------------------------------------------------
# Metric parsing — looks for a line matching "## Best Metric: <number>"
# ---------------------------------------------------------------------------

get_best_metric_from_file() {
    local result_file="$1"
    if [[ ! -f "$result_file" ]]; then
        echo ""
        return
    fi
    grep -oP '##\s*Best Metric[:\s]+\K[0-9]+\.?[0-9]*' "$result_file" 2>/dev/null | head -1
}

# ---------------------------------------------------------------------------
# Input guard — ensures an input file exists; writes a stub if missing
# ---------------------------------------------------------------------------

assert_input_file() {
    local run_dir="$1"
    local filename="$2"
    local consumer_phase="$3"
    local strict_exec="${4:-false}"
    local path="$run_dir/$filename"

    if [[ ! -f "$path" ]]; then
        if [[ "$strict_exec" == "true" ]]; then
            add_blocker_log "$run_dir" "$consumer_phase" "StrictExec: input missing: $filename"
            echo "[ERROR] StrictExec failed: missing input '$filename' for phase '$consumer_phase'" >&2
            return 1
        fi
        echo "    [WARNING] Missing input '$filename' for phase '$consumer_phase' — writing stub"
        write_stub_output "$run_dir" "$filename" "$consumer_phase" \
            "Input file was absent before phase started"
        add_blocker_log "$run_dir" "$consumer_phase" "Input missing: $filename"
    fi
}

# ---------------------------------------------------------------------------
# Experiment command extraction from 06_experiment_plan.md
# ---------------------------------------------------------------------------

get_experiment_commands() {
    local run_dir="$1"
    local plan_file="$run_dir/06_experiment_plan.md"
    if [[ ! -f "$plan_file" ]]; then
        return
    fi

    local in_block=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^\`\`\`(bash|shell|sh|powershell|ps1)?$ ]]; then
            in_block=true
            continue
        fi
        if [[ "$line" =~ ^\`\`\` ]] && [[ "$in_block" == "true" ]]; then
            in_block=false
            continue
        fi
        if [[ "$in_block" == "true" ]]; then
            local trimmed
            trimmed=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [[ -n "$trimmed" && ! "$trimmed" =~ ^# ]]; then
                echo "$trimmed"
            fi
        fi
    done < "$plan_file"
}

# ---------------------------------------------------------------------------
# Phase banner
# ---------------------------------------------------------------------------

write_phase_banner() {
    local phase_name="$1"
    local agent_name="$2"
    local group="$3"
    local line
    line=$(printf '=%.0s' {1..60})
    echo ""
    echo "$line"
    echo " PHASE  : $(echo "$phase_name" | tr '[:lower:]' '[:upper:]')   [Group $group]"
    echo " Agent  : $agent_name"
    echo "$line"
}

# ---------------------------------------------------------------------------
# Template variable resolution
# ---------------------------------------------------------------------------

resolve_run_scoped_command() {
    local cmd="$1"
    local run_dir="$2"
    local topic_slug="$3"
    local root_dir="$4"

    local run_abs
    run_abs=$(cd "$run_dir" 2>/dev/null && pwd || echo "$run_dir")

    local run_rel="$run_abs"
    if [[ "$run_abs" == "$root_dir"* ]]; then
        run_rel="${run_abs#$root_dir/}"
    fi

    cmd="${cmd//\{\{RUN_DIR\}\}/$run_abs}"
    cmd="${cmd//\{\{RUN_DIR_REL\}\}/$run_rel}"
    cmd="${cmd//\{\{TOPIC_SLUG\}\}/$topic_slug}"
    echo "$cmd"
}

# ---------------------------------------------------------------------------
# Color helpers (ANSI)
# ---------------------------------------------------------------------------

_color_red()     { echo -e "\033[0;31m$*\033[0m"; }
_color_green()   { echo -e "\033[0;32m$*\033[0m"; }
_color_yellow()  { echo -e "\033[0;33m$*\033[0m"; }
_color_cyan()    { echo -e "\033[0;36m$*\033[0m"; }
_color_magenta() { echo -e "\033[0;35m$*\033[0m"; }
_color_gray()    { echo -e "\033[0;90m$*\033[0m"; }
_color_white()   { echo -e "\033[0;97m$*\033[0m"; }
