#Requires -Version 5.1
<#
.SYNOPSIS
    Shared helper functions for the RND pipeline.
    Dot-source this file: . "$PSScriptRoot\lib\pipeline-helpers.ps1"
#>

# ---------------------------------------------------------------------------
# State management
# ---------------------------------------------------------------------------

function Read-JsonFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [switch]$ThrowOnError
    )

    if (-not (Test-Path $Path)) {
        if ($ThrowOnError) {
            throw "JSON file not found: $Path"
        }
        return $null
    }

    $encodings = @(
        [System.Text.Encoding]::UTF8,
        [System.Text.Encoding]::Unicode,
        [System.Text.Encoding]::BigEndianUnicode,
        [System.Text.Encoding]::UTF32,
        [System.Text.Encoding]::Default
    )

    $errors = [System.Collections.Generic.List[string]]::new()

    foreach ($enc in $encodings) {
        try {
            $text = [System.IO.File]::ReadAllText($Path, $enc)
            if ([string]::IsNullOrWhiteSpace($text)) {
                continue
            }
            return ($text | ConvertFrom-Json -ErrorAction Stop)
        }
        catch {
            $errors.Add("$($enc.WebName): $($_.Exception.Message)") | Out-Null
        }
    }

    if ($ThrowOnError) {
        $detail = ($errors -join '; ')
        throw "Failed to parse JSON file '$Path'. Attempts: $detail"
    }
    return $null
}

function Read-PipelineState {
    param(
        [string]$RunDir,
        [switch]$ThrowOnError
    )

    $path = Join-Path $RunDir 'state.json'
    if (Test-Path $path) {
        return Read-JsonFile -Path $path -ThrowOnError:$ThrowOnError
    }
    return $null
}

function Write-PipelineState([string]$RunDir, [pscustomobject]$State) {
    $path = Join-Path $RunDir 'state.json'
    $State | ConvertTo-Json -Depth 10 | Set-Content $path -Encoding UTF8
}

function Set-PhaseStatus {
    param(
        [pscustomobject]$State,
        [string]$Phase,
        [string]$Status
    )
    if ($null -eq $State.phase_status) {
        $State | Add-Member -NotePropertyName 'phase_status' `
                            -NotePropertyValue ([pscustomobject]@{}) -Force
    }
    $State.phase_status | Add-Member -NotePropertyName $Phase `
                                     -NotePropertyValue $Status -Force
}

function Get-PhaseStatus {
    param([pscustomobject]$State, [string]$Phase)
    if ($null -eq $State.phase_status) { return $null }
    $prop = $State.phase_status.PSObject.Properties[$Phase]
    if ($null -eq $prop) { return $null }
    return $prop.Value
}

# ---------------------------------------------------------------------------
# Blocker log (one JSON object per line — easy to grep / tail)
# ---------------------------------------------------------------------------

function Add-BlockerLog {
    param(
        [string]$RunDir,
        [string]$Phase,
        [string]$Reason,
        [hashtable]$Meta
    )

    $entry = [ordered]@{
        ts     = (Get-Date -Format 'o')
        phase  = $Phase
        reason = $Reason
    }

    if ($null -ne $Meta -and $Meta.Count -gt 0) {
        $entry.meta = $Meta
    }

    $json = $entry | ConvertTo-Json -Compress -Depth 8
    $logPath = Join-Path $RunDir 'blocker_log.jsonl'
    Add-Content $logPath $json -Encoding UTF8
}

# ---------------------------------------------------------------------------
# Fallback stub output — always writes a non-empty file
# ---------------------------------------------------------------------------

function Write-StubOutput {
    param(
        [string]$RunDir,
        [string]$Filename,
        [string]$Phase,
        [string]$Reason
    )
    $path = Join-Path $RunDir $Filename
    $leafName = [System.IO.Path]::GetFileNameWithoutExtension($Filename)
    $content = @"
# $leafName (STUB — auto-generated by pipeline)

## Status: BLOCKED

| Field     | Value |
|-----------|-------|
| Phase     | $Phase |
| Reason    | $Reason |
| Generated | $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') |

## Best-effort content

No content could be generated for this phase in this run.
Re-run with ``-Resume`` once the blocker is resolved.

## Downstream: Safe to proceed

The pipeline has written this stub so that downstream phases can start
with partial context rather than failing on a missing input file.
"@
    $content | Set-Content $path -Encoding UTF8
    Write-Host "    [STUB] Written: $Filename" -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# Retry wrapper with exponential back-off
# ---------------------------------------------------------------------------

function Invoke-WithRetry {
    param(
        [scriptblock]$Action,
        [string]$Label,
        [int]$MaxAttempts = 3,
        [int]$BaseDelaySec = 30
    )
    for ($i = 1; $i -le $MaxAttempts; $i++) {
        try {
            & $Action
            return $true
        }
        catch {
            $msg = $_.Exception.Message
            Write-Host "    [ATTEMPT $i/$MaxAttempts] $Label — $msg" -ForegroundColor Yellow
            if ($i -lt $MaxAttempts) {
                $delaySec = [int]($BaseDelaySec * [Math]::Pow(2, $i - 1))
                Write-Host "    Waiting ${delaySec}s before next attempt..." -ForegroundColor DarkYellow
                Start-Sleep -Seconds $delaySec
            }
        }
    }
    Write-Host "    [EXHAUSTED] Max retries reached for: $Label" -ForegroundColor Red
    return $false
}

# ---------------------------------------------------------------------------
# Metric parsing — looks for a line matching "## Best Metric: <number>"
#   in the results file and returns it as [double] or $null.
# ---------------------------------------------------------------------------

function Get-BestMetricFromFile([string]$ResultFile) {
    if (-not (Test-Path $ResultFile)) { return $null }
    $content = Get-Content $ResultFile -Raw -Encoding UTF8
    if ($content -match '##\s*Best Metric[:\s]+([0-9]+\.?[0-9]*)') {
        return [double]$Matches[1]
    }
    return $null
}

# ---------------------------------------------------------------------------
# Input guard — ensures an input file exists; writes a stub if missing
# ---------------------------------------------------------------------------

function Assert-InputFile {
    param(
        [string]$RunDir,
        [string]$Filename,
        [string]$ConsumerPhase,
        [switch]$StrictExec
    )
    $path = Join-Path $RunDir $Filename
    if (-not (Test-Path $path)) {
        if ($StrictExec) {
            Add-BlockerLog -RunDir $RunDir -Phase $ConsumerPhase `
                           -Reason "StrictExec: input missing: $Filename"
            throw "StrictExec failed: missing input '$Filename' for phase '$ConsumerPhase'"
        }
        Write-Host "    [WARNING] Missing input '$Filename' for phase '$ConsumerPhase' — writing stub" `
                   -ForegroundColor Yellow
        Write-StubOutput -RunDir $RunDir -Filename $Filename `
                         -Phase $ConsumerPhase `
                         -Reason "Input file was absent before phase started"
        Add-BlockerLog -RunDir $RunDir -Phase $ConsumerPhase `
                       -Reason "Input missing: $Filename"
    }
}

# ---------------------------------------------------------------------------
# Experiment command extraction from 06_experiment_plan.md
# ---------------------------------------------------------------------------

function Get-ExperimentCommands([string]$RunDir) {
    $planFile = Join-Path $RunDir '06_experiment_plan.md'
    if (-not (Test-Path $planFile)) { return @() }

    $content   = Get-Content $planFile -Raw
    $cmds      = [System.Collections.Generic.List[string]]::new()
    $inBlock   = $false
    $blockLang = ''

    foreach ($line in ($content -split "`n")) {
        if ($line -match '^```(bash|shell|sh|powershell|ps1)?$') {
            $inBlock   = $true
            $blockLang = if ($Matches[1]) { $Matches[1] } else { 'sh' }
            continue
        }
        if ($line -match '^```' -and $inBlock) {
            $inBlock = $false
            continue
        }
        if ($inBlock) {
            $trimmed = $line.Trim()
            if ($trimmed -ne '' -and -not $trimmed.StartsWith('#')) {
                $cmds.Add($trimmed)
            }
        }
    }
    return $cmds.ToArray()
}
